# Generated by Django 5.0 on 2024-01-24 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_orders_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='oid',
        ),
        migrations.AddField(
            model_name='product',
            name='global_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.globaldiscount'),
        ),
    ]
