# Generated by Django 5.0 on 2024-01-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_timestamp_orderupdate_time_remove_orders_oid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldiscount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
