# Generated by Django 5.0 on 2024-01-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_globaldiscount_percentage_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldiscount',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
