# Generated by Django 5.0 on 2024-01-26 04:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_cartitem_date_added_remove_cartitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
